import { INVALID } from "zod/v3";

export const ERROR_CODES = {
  FORBIDDEN: "FORBIDDEN",

  BAD_REQUEST: "BAD_REQUEST",

  INVALID_UPLOAD_TYPE: "INVALID_UPLOAD_TYPE",

  UPLOAD_NOT_ALLOWED: "UPLOAD_NOT_ALLOWED",

  VALIDATION_ERROR: "VALIDATION_ERROR",

  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",

  USER_NOT_FOUND: "USER_NOT_FOUND",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  OTP_INVALID: "OTP_INVALID",

  OTP_EXPIRED: "OTP_EXPIRED",

  OTP_RESEND_LIMIT_EXCEEDED: "OTP_RESEND_LIMIT_EXCEEDED",

  UNAUTHORIZED: "UNAUTHORIZED",

  OTP_LIMIT_EXCEEDED: "OTP_LIMIT_EXCEEDED",

  DATABASE_ERROR: "DATABASE_ERROR",

  PAYMENT_FAILED: "PAYMENT_FAILED",

  SEAT_ALREADY_BOOKED: "SEAT_ALREADY_BOOKED",

  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",

  NO_MOVIE_FOUND: 'NO_MOVIE_FOUND',

  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  MOVIE_ALREADY_EXISTS: "MOVIE_ALREADY_EXISTS"
}